<a href="https://colab.research.google.com/github/adamguz92/data-science-bootcamp/blob/main/001_010_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 1](#1)
* [Ćwiczenie 2](#2)
* [Ćwiczenie 3](#3)
* [Ćwiczenie 4](#4)
* [Ćwiczenie 5](#5)
* [Ćwiczenie 6](#6)
* [Ćwiczenie 7](#7)
* [Ćwiczenie 8](#8)
* [Ćwiczenie 9](#9)
* [Ćwiczenie 10](#10)

### <a name='0'></a>Import biblioteki

In [2]:
import numpy as np

np.__version__

'2.0.2'

### <a name='1'></a> Ćwiczenie 1
Sprawdź czy wszystkie elementy tablic $A, B, C$ oraz $D$ zwracają wartość logiczną _True_.



```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```



__Wskazówka:__ Użyj funkcji _np.all()._

In [14]:
A = np.array([3, 2, 1, 4, 5, 2, 1, 6])
A = A.reshape(2, -1)
print(f'A =\n{A}\n')

B = np.array([3, 2, 1, 4, 5, 2, 0, 6]).reshape(2, -1)
print(f'B =\n{B}\n')

C = np.array([[True, False, False],
              [True, True, True]])
print(f'C =\n{C}\n')

D = np.array([0.1, 0.3])
print(f'D =\n{D}\n')

A =
[[3 2 1 4]
 [5 2 1 6]]

B =
[[3 2 1 4]
 [5 2 0 6]]

C =
[[ True False False]
 [ True  True  True]]

D =
[0.1 0.3]



In [22]:
print(f'A = {np.all(A)}\nB = {np.all(B)}\nC = {np.all(C)}\nD = {np.all(D)}')
# np.all() zwraca false gdy w tablicy są wartości false, czyli liczba 0. W przeciwnym razie true.

# Odpowiedź Nie wszystkie elementy tablic A, B, C i D zwracają wartość true.

A = True
B = False
C = False
D = True


### <a name='2'></a> Ćwiczenie 2
Sprawdź czy wszystkie elementy tablic $A, B$ oraz $C$ zwracają wartość logiczną _True_ wzdłuż osi z indeksem 1.


```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```



__Wskazówka:__ Użyj funkcji _np.all()_ z parametrem _axis._

In [24]:
np.all?

In [43]:
np.all(A, axis=0) # axis=0 po kolumnach, axis=1 po wierszach # Brak wartości false.

array([ True,  True,  True,  True])

In [44]:
np.all(B, axis=0) # W kolumnie trzeciej znajduje się wartość false.

array([ True,  True, False,  True])

In [45]:
np.all(C, axis=0) # W kolnie drugiej i trzeciej znajdują się wartości false.

array([ True, False, False])

### <a name='3'></a> Ćwiczenie 3
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```


__Wskazówka:__ Użyj funkcji _np.any()._

In [47]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

np.any(A) # Brak elementu true, czyli tylko wartości 0.

np.False_

In [49]:
np.any(B) # Występują elementy większe niż 0.

np.True_

In [50]:
np.any(C) # Występują elementy większe niż 0.

np.True_

In [51]:
np.any(D)# Występują elementy większe niż 0.

np.True_

### <a name='4'></a> Ćwiczenie 4
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_ wzdłuż osi z indeksem 0.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```



__Wskazówka:__ Użyj funkcji _np.any()_ z parametrem _axis._

In [56]:
np.any(A, axis=1) # axis=1 po wierszach
# Brak wartości T, czyli brak liczb większych od 0.

array([False, False])

In [62]:
np.any(B, axis=1) # Występują wartości frue, czyli równe 0.

array([False,  True])

In [66]:
np.any(C, axis=1) # Występują wartości true, czyli równe 0.

array([False,  True])

In [67]:
np.any(D) # Występują wartości frue, czyli równe 0.

np.True_

### <a name='5'></a> Ćwiczenie 5
Sprawdź tablicę $A$ pod kątem braków danych (_np.nan_).


```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```


__Wskazówka:__ Użyj funkcji _np.isnan()_.

In [76]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])


### <a name='6'></a> Ćwiczenie 6
Sprawdź, czy poniższe tablice $A$ oraz $B$ są równe pod względem elementów (element-wise) z ustalonym poziomem tolerancji. Użyj funkcji _np.allclose()_ z domyślnymi parametrami.



```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
```


In [ ]:
# tutaj wpisz rozwiązanie

### <a name='7'></a> Ćwiczenie 7
Sprawdź, czy poniższe tablice $A$ oraz $B$ są równe pod względem elementów (element-wise). Użyj operatora porównania _==_.


```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
```

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='8'></a> Ćwiczenie 8
Sprawdź, dla których elementów (element-wise) poniższa tablica $A$ ma większe wartości niż tablica $B$.


```
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
```



In [ ]:
# tutaj wpisz rozwiązanie

### <a name='9'></a> Ćwiczenie 9
Stwórz tablicę numpy wymiaru _4x4_ wypełnioną zerami. Ustal typ danych na _int_.

__Oczekiwany wynik:__


```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```



__Wskazówka:__ Użyj funkcji _np.zeros()_.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='10'></a> Ćwiczenie 10
Stwórz tablicę numpy wymiaru _10x10_ wypełnioną liczbą 255. Ustal typ danych na _float_.

__Oczekiwany wynik:__


```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```



__Wskazówka:__ Użyj funkcji _np.ones()_ lub _np.full()_.

In [ ]:
# tutaj wpisz rozwiązanie